name: BuddyTP
version: '${version}'
main: net.bonn2.buddytp.BuddyTP
api-version: 1.17
authors: [ bonn2 ]
description: A limited teleportation system designed for semi-vanilla smps
softdepend:
  - Essentials
commands:
  buddytp:
    description: Teleport to a friend, once
    permission: buddytp.send
    aliases: [ btp ]
    usage: /buddytp <player>
  buddytpaccept:
    description: Accept a teleport request
    permission: buddytp.accept
    aliases: [ btpaccept ]
    usage: /buddytpaccept [player]
  buddytpdeny:
    description: Deny a teleport request
    permission: buddytp.deny
    aliases: [ btpdeny ]
    usage: /buddytpdeny [player]
  buddytpcancel:
    description: Cancel a teleport request
    permission: buddytp.cancel
    aliases: [ btpcancel ]
    usage: /buddytpcancel
  buybuddytp:
    description: Buy a new buddytp
    permission: buddytp.buy
    usage: /buybuddytp
  resetbuddytp:
    description: Reset a players free buddytp
    permission: buddytp.reset
    usage: /resetbuddytp <player>
permissions:
  buddytp.send:
    description: Allows sending buddytp requests
    default: true
  buddytp.accept:
    description: Allows accepting buddytp requests
    default: true
  buddytp.deny:
    description: Allows denying buddytp requests
    default: true
  buddytp.cancel:
    description: Allows a player to cancel buddytp requests
    default: true
  buddytp.buy:
    description: Allows buying a new buddytp
    default: true
  buddytp.reset:
    description: Allows resetting of buddytps
    default: op
